# Week 2 Assignment 

## Part 1 - Numpy

In [1]:
import numpy as np

#### 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [4]:
A = np.array([[1, 7, 3], [2, 9, 6]])
B = np.array([[10, 0, 3], [24, 1, 2]])

vertical_stack = np.vstack((A, B))

horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("\nHorizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[ 1  7  3]
 [ 2  9  6]
 [10  0  3]
 [24  1  2]]

Horizontal Stack:
 [[ 1  7  3 10  0  3]
 [ 2  9  6 24  1  2]]


#### 2. ⁠Find common elements between A and B.

In [5]:
common_elements = np.intersect1d(A, B)
print("\nCommon Elements between A and B:", common_elements)


Common Elements between A and B: [1 2 3]


#### 3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10.

In [6]:
filtered_A = A[(A >= 5) & (A <= 10)]
print("\nElements in A between 5 and 10:", filtered_A)


Elements in A between 5 and 10: [7 9 6]


#### 4. ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [8]:
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("\nFiltered iris_2d rows:\n", filtered_iris)


Filtered iris_2d rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## Part 2 - Pandas

In [9]:
import pandas as pd

#### 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]
print("\nFiltered DataFrame (Every 20th Row):\n", filtered_df)


Filtered DataFrame (Every 20th Row):
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


#### 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [12]:
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())


#### 3. How to get the rows of a dataframe with row sum > 100?

In [20]:
df_random = pd.DataFrame(np.random.randint(10, 40, size=(15, 4)))
filtered_rows = df_random[df_random.sum(axis=1) > 100]

print("\nRows where the total sum per row is greater than 100:\n", filtered_rows)


Rows where the total sum per row is greater than 100:
      0   1   2   3
0   24  39  21  36
1   25  39  30  25
7   33  37  28  13
9   25  26  16  34
10  28  38  19  27
14  39  13  13  37
